SRC_DIR=./..

LIBNAME = libdsp
FULLNAME = $(LIB_DIR)/$(LIBNAME).a

include $(SRC_DIR)/rules.mk

CFLAGS += -I./                      \
          -I$(SRC_DIR)/include      \
          -I$(SRC_DIR)/libhardware  \
          -I$(SRC_DIR)/libcmsis     \
          -I$(SRC_DIR)/libdsp     \
          $(HARDWARE_DEFS)





